### ISSUE TITLE
smbc returns model with empty type even though a val of this type was declared

### ISSUE THREAD

**Issue by samuelgruetter** [c-cube/smbc#5]
Description of problem: see [here](https://github.com/nunchaku-inria/nunchaku/issues/29#issuecomment-429572887).

**Comment by c-cube** [comment]
I'll take a look, thank you.

**Comment by c-cube** [comment]
Empty types will always be completed now. It never hurts to do that.

**Comment by samuelgruetter** [comment]
> Empty types will always be completed now. It never hurts to do that.

Even if I have `axiom forall (v: MyEmptyType). false.` ?

**Comment by c-cube** [comment]
Hmmm I'd consider that as unsat, but that's an interesting point. I suppose `exists (v:foo). true` would be used to make a type non empty? I'm not used to reasoning with possibly empty types, tbh.

(cc @blanchette for opinions on the topic)

**Comment by blanchette** [comment]
Hi Simon,

Nunchaku and (to the best of my knowledge and *hope*, SMBC) are based on simple type theory, in which all types are inhabited.

Cheers,

Jasmin

**Comment by c-cube** [comment]
@blanchette yes, datatypes are always inhabited. Uninterpreted types are, too, but this bug occurs in the case where a type is never touched (no value in it is ever used), so the printed model was empty :-)
I guess that's the way things should continue to be, then. Thank you.
